// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"processor/internal/biz"
	"processor/internal/conf"
	"processor/internal/data"
	"processor/internal/server"
	"processor/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*app, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	imageRepo := data.NewImageRepo(dataData, logger)
	imageUsecase := biz.NewImageUsecase(imageRepo, logger)
	imageService := service.NewImageService(imageUsecase, logger)
	eventsServer, err := server.NewConsumerServer(confServer, imageService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApp := newApp(eventsServer)
	return mainApp, func() {
		cleanup()
	}, nil
}
