server:
  http:
    endpoint: 0.0.0.0:8080
data:
  database:
    driver: mysql
    source: root:password@tcp(localhost:3306)/test?parseTime=True&loc=Local
  redis:
    endpoint: localhost:6379
    dial_timeout: 1s
    read_timeout: 1s
    write_timeout: 1s
  minio:
    endpoint: localhost:9000
    access_key: user
    secret_key: password
  rabbitmq:
    endpoint: localhost:5672
    connections: 5
    username: user
    password: password
