// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsImageNotSupported(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IMAGE_NOT_SUPPORTED.String() && e.Code == 400
}

func ErrorImageNotSupported(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_IMAGE_NOT_SUPPORTED.String(), fmt.Sprintf(format, args...))
}

func IsImageNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IMAGE_NOT_FOUND.String() && e.Code == 404
}

func ErrorImageNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_IMAGE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsInvalidImageTransformations(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_IMAGE_TRANSFORMATIONS.String() && e.Code == 400
}

func ErrorInvalidImageTransformations(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_IMAGE_TRANSFORMATIONS.String(), fmt.Sprintf(format, args...))
}
