// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package msgp

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Crop) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "width":
			z.Width, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "height":
			z.Height, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Height")
				return
			}
		case "y":
			z.X, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "x":
			z.Y, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Crop) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "width"
	err = en.Append(0x84, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Width)
	if err != nil {
		err = msgp.WrapError(err, "Width")
		return
	}
	// write "height"
	err = en.Append(0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Height)
	if err != nil {
		err = msgp.WrapError(err, "Height")
		return
	}
	// write "y"
	err = en.Append(0xa1, 0x79)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.X)
	if err != nil {
		err = msgp.WrapError(err, "X")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Y)
	if err != nil {
		err = msgp.WrapError(err, "Y")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Crop) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "width"
	o = append(o, 0x84, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
	o = msgp.AppendUint32(o, z.Width)
	// string "height"
	o = append(o, 0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.Height)
	// string "y"
	o = append(o, 0xa1, 0x79)
	o = msgp.AppendUint32(o, z.X)
	// string "x"
	o = append(o, 0xa1, 0x78)
	o = msgp.AppendUint32(o, z.Y)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Crop) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "width":
			z.Width, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "height":
			z.Height, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Height")
				return
			}
		case "y":
			z.X, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "x":
			z.Y, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Crop) Msgsize() (s int) {
	s = 1 + 6 + msgp.Uint32Size + 7 + msgp.Uint32Size + 2 + msgp.Uint32Size + 2 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EventType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint32
		zb0001, err = dc.ReadUint32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = EventType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z EventType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint32(uint32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EventType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint32(o, uint32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EventType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint32
		zb0001, bts, err = msgp.ReadUint32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = EventType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EventType) Msgsize() (s int) {
	s = msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FailedImageTranformationEvent) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "image_id":
			z.ImageId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "transformation_id":
			z.TransformationId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		case "reason":
			z.Reason, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Reason")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z FailedImageTranformationEvent) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "image_id"
	err = en.Append(0x83, 0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImageId)
	if err != nil {
		err = msgp.WrapError(err, "ImageId")
		return
	}
	// write "transformation_id"
	err = en.Append(0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.TransformationId)
	if err != nil {
		err = msgp.WrapError(err, "TransformationId")
		return
	}
	// write "reason"
	err = en.Append(0xa6, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Reason)
	if err != nil {
		err = msgp.WrapError(err, "Reason")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z FailedImageTranformationEvent) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "image_id"
	o = append(o, 0x83, 0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ImageId)
	// string "transformation_id"
	o = append(o, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.TransformationId)
	// string "reason"
	o = append(o, 0xa6, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Reason)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FailedImageTranformationEvent) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "image_id":
			z.ImageId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "transformation_id":
			z.TransformationId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		case "reason":
			z.Reason, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Reason")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z FailedImageTranformationEvent) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.ImageId) + 18 + msgp.StringPrefixSize + len(z.TransformationId) + 7 + msgp.StringPrefixSize + len(z.Reason)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Filter) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "grayscale":
			z.Grayscale, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Grayscale")
				return
			}
		case "sepia":
			z.Sepia, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Sepia")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Filter) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "grayscale"
	err = en.Append(0x82, 0xa9, 0x67, 0x72, 0x61, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Grayscale)
	if err != nil {
		err = msgp.WrapError(err, "Grayscale")
		return
	}
	// write "sepia"
	err = en.Append(0xa5, 0x73, 0x65, 0x70, 0x69, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Sepia)
	if err != nil {
		err = msgp.WrapError(err, "Sepia")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Filter) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "grayscale"
	o = append(o, 0x82, 0xa9, 0x67, 0x72, 0x61, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x65)
	o = msgp.AppendBool(o, z.Grayscale)
	// string "sepia"
	o = append(o, 0xa5, 0x73, 0x65, 0x70, 0x69, 0x61)
	o = msgp.AppendBool(o, z.Sepia)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Filter) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "grayscale":
			z.Grayscale, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Grayscale")
				return
			}
		case "sepia":
			z.Sepia, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sepia")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Filter) Msgsize() (s int) {
	s = 1 + 10 + msgp.BoolSize + 6 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Resize) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "width":
			z.Width, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "height":
			z.Height, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Height")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Resize) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "width"
	err = en.Append(0x82, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Width)
	if err != nil {
		err = msgp.WrapError(err, "Width")
		return
	}
	// write "height"
	err = en.Append(0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Height)
	if err != nil {
		err = msgp.WrapError(err, "Height")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Resize) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "width"
	o = append(o, 0x82, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
	o = msgp.AppendUint32(o, z.Width)
	// string "height"
	o = append(o, 0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.Height)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Resize) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "width":
			z.Width, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Width")
				return
			}
		case "height":
			z.Height, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Height")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Resize) Msgsize() (s int) {
	s = 1 + 6 + msgp.Uint32Size + 7 + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Transformations) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "transformation_id":
			z.TransformationId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		case "username":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "image_id":
			z.ImageId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "resize":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Resize")
					return
				}
				z.Resize = nil
			} else {
				if z.Resize == nil {
					z.Resize = new(Resize)
				}
				var zb0002 uint32
				zb0002, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Resize")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Resize")
						return
					}
					switch msgp.UnsafeString(field) {
					case "width":
						z.Resize.Width, err = dc.ReadUint32()
						if err != nil {
							err = msgp.WrapError(err, "Resize", "Width")
							return
						}
					case "height":
						z.Resize.Height, err = dc.ReadUint32()
						if err != nil {
							err = msgp.WrapError(err, "Resize", "Height")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Resize")
							return
						}
					}
				}
			}
		case "crop":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Crop")
					return
				}
				z.Crop = nil
			} else {
				if z.Crop == nil {
					z.Crop = new(Crop)
				}
				err = z.Crop.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Crop")
					return
				}
			}
		case "rotate":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Rotate")
					return
				}
				z.Rotate = nil
			} else {
				if z.Rotate == nil {
					z.Rotate = new(uint32)
				}
				*z.Rotate, err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "Rotate")
					return
				}
			}
		case "format":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Format")
					return
				}
				z.Format = nil
			} else {
				if z.Format == nil {
					z.Format = new(string)
				}
				*z.Format, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Format")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Transformations) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "transformation_id"
	err = en.Append(0x87, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.TransformationId)
	if err != nil {
		err = msgp.WrapError(err, "TransformationId")
		return
	}
	// write "username"
	err = en.Append(0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "image_id"
	err = en.Append(0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImageId)
	if err != nil {
		err = msgp.WrapError(err, "ImageId")
		return
	}
	// write "resize"
	err = en.Append(0xa6, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	if z.Resize == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 2
		// write "width"
		err = en.Append(0x82, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Resize.Width)
		if err != nil {
			err = msgp.WrapError(err, "Resize", "Width")
			return
		}
		// write "height"
		err = en.Append(0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.Resize.Height)
		if err != nil {
			err = msgp.WrapError(err, "Resize", "Height")
			return
		}
	}
	// write "crop"
	err = en.Append(0xa4, 0x63, 0x72, 0x6f, 0x70)
	if err != nil {
		return
	}
	if z.Crop == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Crop.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Crop")
			return
		}
	}
	// write "rotate"
	err = en.Append(0xa6, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	if z.Rotate == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteUint32(*z.Rotate)
		if err != nil {
			err = msgp.WrapError(err, "Rotate")
			return
		}
	}
	// write "format"
	err = en.Append(0xa6, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74)
	if err != nil {
		return
	}
	if z.Format == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.Format)
		if err != nil {
			err = msgp.WrapError(err, "Format")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Transformations) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "transformation_id"
	o = append(o, 0x87, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.TransformationId)
	// string "username"
	o = append(o, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "image_id"
	o = append(o, 0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ImageId)
	// string "resize"
	o = append(o, 0xa6, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65)
	if z.Resize == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 2
		// string "width"
		o = append(o, 0x82, 0xa5, 0x77, 0x69, 0x64, 0x74, 0x68)
		o = msgp.AppendUint32(o, z.Resize.Width)
		// string "height"
		o = append(o, 0xa6, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
		o = msgp.AppendUint32(o, z.Resize.Height)
	}
	// string "crop"
	o = append(o, 0xa4, 0x63, 0x72, 0x6f, 0x70)
	if z.Crop == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Crop.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Crop")
			return
		}
	}
	// string "rotate"
	o = append(o, 0xa6, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x65)
	if z.Rotate == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendUint32(o, *z.Rotate)
	}
	// string "format"
	o = append(o, 0xa6, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74)
	if z.Format == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.Format)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Transformations) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "transformation_id":
			z.TransformationId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		case "username":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "image_id":
			z.ImageId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "resize":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Resize = nil
			} else {
				if z.Resize == nil {
					z.Resize = new(Resize)
				}
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Resize")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Resize")
						return
					}
					switch msgp.UnsafeString(field) {
					case "width":
						z.Resize.Width, bts, err = msgp.ReadUint32Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Resize", "Width")
							return
						}
					case "height":
						z.Resize.Height, bts, err = msgp.ReadUint32Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Resize", "Height")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Resize")
							return
						}
					}
				}
			}
		case "crop":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Crop = nil
			} else {
				if z.Crop == nil {
					z.Crop = new(Crop)
				}
				bts, err = z.Crop.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Crop")
					return
				}
			}
		case "rotate":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Rotate = nil
			} else {
				if z.Rotate == nil {
					z.Rotate = new(uint32)
				}
				*z.Rotate, bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Rotate")
					return
				}
			}
		case "format":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Format = nil
			} else {
				if z.Format == nil {
					z.Format = new(string)
				}
				*z.Format, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Format")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Transformations) Msgsize() (s int) {
	s = 1 + 18 + msgp.StringPrefixSize + len(z.TransformationId) + 9 + msgp.StringPrefixSize + len(z.Username) + 9 + msgp.StringPrefixSize + len(z.ImageId) + 7
	if z.Resize == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 6 + msgp.Uint32Size + 7 + msgp.Uint32Size
	}
	s += 5
	if z.Crop == nil {
		s += msgp.NilSize
	} else {
		s += z.Crop.Msgsize()
	}
	s += 7
	if z.Rotate == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Uint32Size
	}
	s += 7
	if z.Format == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.Format)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TransformedImageEvent) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "image_id":
			z.ImageId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "transformation_id":
			z.TransformationId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TransformedImageEvent) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "image_id"
	err = en.Append(0x82, 0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ImageId)
	if err != nil {
		err = msgp.WrapError(err, "ImageId")
		return
	}
	// write "transformation_id"
	err = en.Append(0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.TransformationId)
	if err != nil {
		err = msgp.WrapError(err, "TransformationId")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TransformedImageEvent) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "image_id"
	o = append(o, 0x82, 0xa8, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ImageId)
	// string "transformation_id"
	o = append(o, 0xb1, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.TransformationId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TransformedImageEvent) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "image_id":
			z.ImageId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ImageId")
				return
			}
		case "transformation_id":
			z.TransformationId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TransformationId")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TransformedImageEvent) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.ImageId) + 18 + msgp.StringPrefixSize + len(z.TransformationId)
	return
}
