// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"manager/internal/auth"
	"manager/internal/biz"
	"manager/internal/conf"
	"manager/internal/data"
	"manager/internal/server"
	"manager/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confAuth *conf.Auth, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	jwtAuthenticator, err := auth.NewJwtAuthenticator(confAuth)
	if err != nil {
		return nil, nil, err
	}
	passwordGenerator := auth.NewPasswordGenerator()
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(jwtAuthenticator, passwordGenerator, userRepo)
	userService := service.NewUserService(userUsecase, logger)
	imageService := service.NewImageService(logger)
	httpServer := server.NewHTTPServer(confServer, jwtAuthenticator, userService, imageService, logger)
	app := newApp(logger, httpServer, confServer)
	return app, func() {
		cleanup()
	}, nil
}
