// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsInvalidUsernameOrPassword(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_USERNAME_OR_PASSWORD.String() && e.Code == 400
}

func ErrorInvalidUsernameOrPassword(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_USERNAME_OR_PASSWORD.String(), fmt.Sprintf(format, args...))
}

func IsUsernameAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_ALREADY_EXISTS.String() && e.Code == 400
}

func ErrorUsernameAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USERNAME_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
